name: Demo - Build and Deploy
on:
    push:
        tags:
            - release/*
    # Enable manual trigger
    workflow_dispatch:
jobs:
  demo-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Build
        run: echo -e "node_modules/ \n.DS_Store \n*.log \n.idea \n*.orig \nlib/ \nNOTES.txt \nstyleguide/ \n" >> .gitignore
      - run: npm run build
      - run: cp -R dist styleguide/
      - run: cp -R demo styleguide/
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: styleguide
